export const CATEGORY_ICONS: Record<string, string> = {
  bikes: '🚲',
  mobility: '🛴',
  tools: '🔧',
  electronics: '💻',
  sports: '⚽',
  furniture: '🪑',
  books: '📚',
  music: '🎸',
  toys: '🧸',
  other: '📦',
};

export const DEFAULT_CATEGORIES = [
  {
    name: 'Tools & DIY',
    slug: 'tools',
    description: 'Tools, power tools, and DIY equipment for rent',
    icon: CATEGORY_ICONS.tools,
    color: '#F59E0B',
    sortOrder: 1,
    isActive: true,
  },
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Cameras, computers, and electronic devices',
    icon: CATEGORY_ICONS.electronics,
    color: '#3B82F6',
    sortOrder: 2,
    isActive: true,
  },
  {
    name: 'Sports & Outdoor',
    slug: 'sports',
    description: 'Sports equipment and outdoor gear',
    icon: CATEGORY_ICONS.sports,
    color: '#10B981',
    sortOrder: 3,
    isActive: true,
  },
  {
    name: 'Bikes & Mobility',
    slug: 'bikes',
    description: 'Bicycles, scooters, and mobility devices',
    icon: CATEGORY_ICONS.bikes,
    color: '#EC4899',
    sortOrder: 4,
    isActive: true,
  },
  {
    name: 'Furniture',
    slug: 'furniture',
    description: 'Furniture and home furnishings',
    icon: CATEGORY_ICONS.furniture,
    color: '#8B5CF6',
    sortOrder: 5,
    isActive: true,
  },
  {
    name: 'Music & Audio',
    slug: 'music',
    description: 'Musical instruments and audio equipment',
    icon: CATEGORY_ICONS.music,
    color: '#EF4444',
    sortOrder: 6,
    isActive: true,
  },
  {
    name: 'Books & Media',
    slug: 'books',
    description: 'Books, movies, and media',
    icon: CATEGORY_ICONS.books,
    color: '#6366F1',
    sortOrder: 7,
    isActive: true,
  },
  {
    name: 'Toys & Games',
    slug: 'toys',
    description: 'Toys, games, and hobbies',
    icon: CATEGORY_ICONS.toys,
    color: '#F97316',
    sortOrder: 8,
    isActive: true,
  },
  {
    name: 'Other',
    slug: 'other',
    description: 'Other items',
    icon: CATEGORY_ICONS.other,
    color: '#6B7280',
    sortOrder: 99,
    isActive: true,
  },
];

export const DEFAULT_TAGS = [
  {
    name: 'Outdoor',
    slug: 'outdoor',
    description: 'Suitable for outdoor use',
    isActive: true,
  },
  {
    name: 'Indoor',
    slug: 'indoor',
    description: 'Suitable for indoor use',
    isActive: true,
  },
  {
    name: 'Portable',
    slug: 'portable',
    description: 'Easy to transport',
    isActive: true,
  },
  {
    name: 'Professional',
    slug: 'professional',
    description: 'Professional grade equipment',
    isActive: true,
  },
  {
    name: 'Beginner-friendly',
    slug: 'beginner-friendly',
    description: 'Suitable for beginners',
    isActive: true,
  },
  {
    name: 'Electric',
    slug: 'electric',
    description: 'Electric powered',
    isActive: true,
  },
  {
    name: 'Manual',
    slug: 'manual',
    description: 'Manual/non-electric',
    isActive: true,
  },
  {
    name: 'Heavy-duty',
    slug: 'heavy-duty',
    description: 'Built for heavy use',
    isActive: true,
  },
  {
    name: 'Luxury',
    slug: 'luxury',
    description: 'Premium/luxury item',
    isActive: true,
  },
  {
    name: 'Budget-friendly',
    slug: 'budget-friendly',
    description: 'Affordable option',
    isActive: true,
  },
  {
    name: 'Popular',
    slug: 'popular',
    description: 'Popular item',
    isActive: true,
  },
  {
    name: 'Verified',
    slug: 'verified',
    description: 'Verified by admin',
    isActive: true,
  },
  {
    name: 'Fragile',
    slug: 'fragile',
    description: 'Handle with care',
    isActive: true,
  },
  {
    name: 'Large item',
    slug: 'large-item',
    description: 'Requires special handling',
    isActive: true,
  },
  {
    name: 'Weekend use',
    slug: 'weekend-use',
    description: 'Best for weekend rental',
    isActive: true,
  },
  {
    name: 'Daily use',
    slug: 'daily-use',
    description: 'Suitable for daily rental',
    isActive: true,
  },
  {
    name: 'Delivery available',
    slug: 'delivery-available',
    description: 'Delivery can be arranged',
    isActive: true,
  },
];
